### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by saeedalsnfawy** [EthanC/Sleuth#4]
Sleuth - Fortnite News Feed watcher
https://github.com/EthanC/Sleuth

[12:10:55] Loaded configuration
[12:10:56] Retrieved the current Fortnite News Feed
[12:10:56] No changes found in News Feed
and no img saved or posted on twitter

**Comment by EthanC** [comment]
It won't post the News Feed every time you run the script. It's intended to be ran on a schedule and whenever a change is detected, it will post that change to Twitter.

**Comment by saeedalsnfawy** [comment]
Ok!
